name = "slum"
license = "MIT"
licenselink = "https://github.com/djnavarro/hugo-slum/blob/master/LICENSE.md"
description = "SLUM: A minimal Hugo theme for blogdown"
homepage = "https://github.com/djnavarro/hugo-slum/"
tags = ["minimal", "blog", "personal"]
features = ["blog"]
min_version = "0.0.1"

[author]
  name = "Danielle Navarro"
  homepage = "https://djnavarro.net"
