name = "calade"
license = "MIT"
licenselink = "https://github.com/djnavarro/hugo-calade/blob/master/LICENSE.md"
description = "Calade: A minimal Hugo theme for R users"
homepage = "https://github.com/djnavarro/hugo-calade/"
tags = ["minimal", "blog", "personal"]
features = ["blog"]
min_version = "0.0.1"

[author]
  name = "Danielle Navarro"
  homepage = "https://djnavarro.net"
